steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '--build-arg'
      - 'VITE_SUPABASE_URL=$_VITE_SUPABASE_URL'
      - '--build-arg'
      - 'VITE_SUPABASE_ANON_KEY=$_VITE_SUPABASE_ANON_KEY'
      - '-t'
      - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME:$COMMIT_SHA'
      - '-f'
      - 'Dockerfile'
      - '.'
    id: Build

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME:$COMMIT_SHA'
    id: Push

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - '$_SERVICE_NAME'
      - '--platform=managed'
      - '--image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME:$COMMIT_SHA'
      - '--region=$_DEPLOY_REGION'
      - '--quiet'

images:
  - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
